\documentclass{beamer}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Lecture 13 - Apply and Likelihood
%%%   
%%%
%%% Last Modified 10/15/2012
%%%
%%% Changelog:
%%% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%\input{handoutPreamble.Rnw} %for when we use the handout argument for documentclass
\input{slidePreamble.Rnw}

%%%%%load in code chunks, and run some preperatory code
<<set-options, echo=FALSE, cache=FALSE, include=FALSE>>=
source("./beamerPrep.R")
read_chunk("./lecture_13.R")

opts_chunk$set(size = "footnotesize")
opts_chunk$set(fig.align = "center")
opts_chunk$set(out.height="0.55\\textwidth")
opts_chunk$set(out.width="0.55\\textwidth")
opts_chunk$set(tidy=FALSE)
opts_chunk$set(prompt=FALSE)
opts_chunk$set(comment="#")

par(mar=c(5,4,2,2))
@

<<lecture13prep, echo=FALSE, cache=TRUE, include=FALSE>>=
@


\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\huge Iteration, Likelihood, and All That

\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{For Loops!}

<<forBad, eval=FALSE, size="Large", tidy=FALSE>>=
x<-1:100000
#
for (i in x){
  x[i]<-x[i] +1  
}
@
\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{For Loops: Costs \& Benefits}
Benefits:
\begin{enumerate}
 \item Minimal code for repetitive actions
 \item Can map same operation across a vectore, matrix, list, etc.
\end{enumerate} 

\hfill \\
Costs:
\begin{enumerate}
 \item Slow.
 \item Lots of Code.
\end{enumerate} 

\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{Speed: Many Operations Faster via \emph{Vectorization}}

<<vectorize1, size="Large">>=
@

\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{Many Operations Faster via \emph{Vectorization}}

<<Timevectorize1, cache=TRUE>>=
@

\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{Vectorization Ubiquitos}

<<vectorize2, size="normalsize", tidy=TRUE>>=
@
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{Vectorization Ambiguous in Many Instances...}

<<vectorizationBad, size="normalsize">>=
@
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{How to \tt{Vectorize} Ambiguous Functions}

<<vectorizationGood, size="normalsize">>=
@
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{The Guts of \tt{Vectorize}}

<<vectorizationGuts>>=
@
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{Minimizing Code for Mapping Functions: the Apply Family}

Take an object type - vector, matrix, list, etc., and map a function to every element, cleanly and quickly.
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[fragile]
\frametitle{sapply for Vectors}

<<sapply1, size="normalsize">>=
@
\end{frame}




\end{document}